color_range_list:
  ball:
    max:
    - 180
    - 180
    - 150
    min:
    - 0
    - 160
    - 0
  black:
    max:
    - 45
    - 150
    - 150
    min:
    - 0
    - 100
    - 100
  blue:
    max:
    - 233
    - 134
    - 121
    min:
    - 58
    - 88
    - 0
  green:
    max:
    - 255
    - 103
    - 195
    min:
    - 86
    - 11
    - 15
  red:
    max:
    - 242
    - 255
    - 255
    min:
    - 76
    - 157
    - 98
  tennis:
    max:
    - 255
    - 116
    - 181
    min:
    - 19
    - 79
    - 140
  white:
    max:
    - 255
    - 155
    - 155
    min:
    - 110
    - 100
    - 100
  yellow:
    max:
    - 255
    - 177
    - 184
    min:
    - 195
    - 110
    - 146
